# Generated by Django 5.1.1 on 2025-10-14 23:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taxonomy', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='course',
            options={'ordering': ['title'], 'verbose_name': 'Курс', 'verbose_name_plural': 'Курсы'},
        ),
        migrations.AlterModelOptions(
            name='courseskill',
            options={'verbose_name': 'Навык курса', 'verbose_name_plural': 'Навыки курсов'},
        ),
        migrations.AlterModelOptions(
            name='skill',
            options={'ordering': ['name'], 'verbose_name': 'Навык', 'verbose_name_plural': 'Навыки'},
        ),
        migrations.AlterField(
            model_name='course',
            name='description',
            field=models.TextField(blank=True, default='', verbose_name='описание'),
        ),
        migrations.AlterField(
            model_name='course',
            name='difficulty',
            field=models.CharField(choices=[('beginner', 'Начинающий'), ('intermediate', 'Средний'), ('advanced', 'Продвинутый')], default='beginner', max_length=20, verbose_name='сложность'),
        ),
        migrations.AlterField(
            model_name='course',
            name='duration_hours',
            field=models.PositiveIntegerField(default=0, verbose_name='длительность (часы)'),
        ),
        migrations.AlterField(
            model_name='course',
            name='provider',
            field=models.CharField(blank=True, default='', max_length=120, verbose_name='провайдер'),
        ),
        migrations.AlterField(
            model_name='course',
            name='title',
            field=models.CharField(max_length=200, verbose_name='название'),
        ),
        migrations.AlterField(
            model_name='courseskill',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_skills', to='taxonomy.course', verbose_name='курс'),
        ),
        migrations.AlterField(
            model_name='courseskill',
            name='coverage_weight',
            field=models.DecimalField(decimal_places=2, default=1.0, max_digits=3, verbose_name='вес покрытия'),
        ),
        migrations.AlterField(
            model_name='courseskill',
            name='skill',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skill_courses', to='taxonomy.skill', verbose_name='навык'),
        ),
        migrations.AlterField(
            model_name='skill',
            name='category',
            field=models.CharField(blank=True, default='', max_length=120, verbose_name='категория'),
        ),
        migrations.AlterField(
            model_name='skill',
            name='description',
            field=models.TextField(blank=True, default='', verbose_name='описание'),
        ),
        migrations.AlterField(
            model_name='skill',
            name='name',
            field=models.CharField(max_length=120, unique=True, verbose_name='название'),
        ),
    ]
