# Generated by Django 5.1.1 on 2025-10-12 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('website', models.URLField(blank=True, default='')),
                ('email_domain', models.CharField(blank=True, default='', help_text='example: epam.com', max_length=120)),
                ('category', models.CharField(choices=[('tech', 'Tech / IT'), ('engineering', 'Engineering'), ('marketing', 'Marketing'), ('gamedev', 'GameDev'), ('other', 'Other')], default='tech', max_length=20)),
                ('about_text', models.TextField(blank=True, default='')),
                ('is_trusted', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
                'indexes': [models.Index(fields=['category'], name='companies_c_categor_0d60ed_idx'), models.Index(fields=['status'], name='companies_c_status_2407e4_idx')],
            },
        ),
    ]
