# Generated by Django 5.1.1 on 2025-10-12 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0002_industry_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='company',
            options={'ordering': ['name'], 'verbose_name': 'Компания', 'verbose_name_plural': 'Компании'},
        ),
        migrations.AlterModelOptions(
            name='industry',
            options={'ordering': ['name'], 'verbose_name': 'Направление (категория)', 'verbose_name_plural': 'Направления (категории)'},
        ),
        migrations.AlterField(
            model_name='company',
            name='about_text',
            field=models.TextField(blank=True, default='', verbose_name='о компании'),
        ),
        migrations.AlterField(
            model_name='company',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='создано'),
        ),
        migrations.AlterField(
            model_name='company',
            name='email_domain',
            field=models.CharField(blank=True, default='', help_text='Напр.: epam.com — пригодится для быстрой верификации', max_length=120, verbose_name='домен почты'),
        ),
        migrations.AlterField(
            model_name='company',
            name='industries',
            field=models.ManyToManyField(blank=True, help_text='Выберите одно или несколько направлений деятельности', related_name='companies', to='companies.industry', verbose_name='направления (категории)'),
        ),
        migrations.AlterField(
            model_name='company',
            name='is_trusted',
            field=models.BooleanField(default=False, verbose_name='доверенный работодатель'),
        ),
        migrations.AlterField(
            model_name='company',
            name='name',
            field=models.CharField(max_length=200, unique=True, verbose_name='название компании'),
        ),
        migrations.AlterField(
            model_name='company',
            name='status',
            field=models.CharField(choices=[('pending', 'На модерации'), ('approved', 'Одобрена'), ('rejected', 'Отклонена')], default='pending', help_text='Управляет публикацией вакансий: одобрена/на модерации/отклонена', max_length=20, verbose_name='статус модерации'),
        ),
        migrations.AlterField(
            model_name='company',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='обновлено'),
        ),
        migrations.AlterField(
            model_name='company',
            name='website',
            field=models.URLField(blank=True, default='', verbose_name='сайт'),
        ),
        migrations.AlterField(
            model_name='industry',
            name='name',
            field=models.CharField(max_length=120, unique=True, verbose_name='название'),
        ),
        migrations.AlterField(
            model_name='industry',
            name='slug',
            field=models.SlugField(help_text='Короткий код латиницей — например backend, devops', unique=True, verbose_name='слаг'),
        ),
    ]
