# Generated by Django 5.1.1 on 2025-10-12 16:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '0001_initial'),
        ('taxonomy', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vacancy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description_md', models.TextField()),
                ('grade', models.CharField(choices=[('intern', 'Intern'), ('junior', 'Junior'), ('middle', 'Middle'), ('senior', 'Senior')], default='junior', max_length=12)),
                ('employment_type', models.CharField(choices=[('fulltime', 'Full-time'), ('parttime', 'Part-time'), ('internship', 'Internship'), ('contract', 'Contract')], default='fulltime', max_length=12)),
                ('location', models.CharField(blank=True, default='', max_length=120)),
                ('is_remote', models.BooleanField(default=True)),
                ('salary_min', models.PositiveIntegerField(blank=True, null=True)),
                ('salary_max', models.PositiveIntegerField(blank=True, null=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('moderation', 'On moderation'), ('published', 'Published'), ('archived', 'Archived')], default='moderation', max_length=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vacancies', to='companies.company')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='VacancySkill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.IntegerField(choices=[(1, 'Nice-to-have'), (2, 'Required')], default=2)),
                ('skill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skill_vacancies', to='taxonomy.skill')),
                ('vacancy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vacancy_skills', to='vacancies.vacancy')),
            ],
        ),
        migrations.AddField(
            model_name='vacancy',
            name='skills',
            field=models.ManyToManyField(related_name='vacancies', through='vacancies.VacancySkill', to='taxonomy.skill'),
        ),
        migrations.AddConstraint(
            model_name='vacancyskill',
            constraint=models.UniqueConstraint(fields=('vacancy', 'skill'), name='uq_vacancy_skill'),
        ),
        migrations.AddIndex(
            model_name='vacancy',
            index=models.Index(fields=['status'], name='vacancies_v_status_7f8d7e_idx'),
        ),
        migrations.AddIndex(
            model_name='vacancy',
            index=models.Index(fields=['grade'], name='vacancies_v_grade_a3a7e8_idx'),
        ),
        migrations.AddIndex(
            model_name='vacancy',
            index=models.Index(fields=['employment_type'], name='vacancies_v_employm_6a03e0_idx'),
        ),
    ]
