# Generated by Django 5.1.1 on 2025-10-14 23:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0003_alter_company_options_alter_industry_options_and_more'),
        ('taxonomy', '0002_alter_course_options_alter_courseskill_options_and_more'),
        ('vacancies', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vacancy',
            options={'ordering': ['-created_at'], 'verbose_name': 'Вакансия', 'verbose_name_plural': 'Вакансии'},
        ),
        migrations.AlterModelOptions(
            name='vacancyskill',
            options={'verbose_name': 'Навык вакансии', 'verbose_name_plural': 'Навыки вакансий'},
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vacancies', to='companies.company', verbose_name='компания'),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='создано'),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='description_md',
            field=models.TextField(verbose_name='описание'),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='employment_type',
            field=models.CharField(choices=[('fulltime', 'Полная занятость'), ('parttime', 'Частичная занятость'), ('internship', 'Стажировка'), ('contract', 'Контракт')], default='fulltime', max_length=12, verbose_name='тип занятости'),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='grade',
            field=models.CharField(choices=[('intern', 'Стажер'), ('junior', 'Джуниор'), ('middle', 'Мидл'), ('senior', 'Сеньор')], default='junior', max_length=12, verbose_name='уровень'),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='is_remote',
            field=models.BooleanField(default=True, verbose_name='удаленная работа'),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='location',
            field=models.CharField(blank=True, default='', max_length=120, verbose_name='локация'),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='salary_max',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='макс. зарплата'),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='salary_min',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='мин. зарплата'),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='skills',
            field=models.ManyToManyField(related_name='vacancies', through='vacancies.VacancySkill', to='taxonomy.skill', verbose_name='навыки'),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='status',
            field=models.CharField(choices=[('draft', 'Черновик'), ('moderation', 'На модерации'), ('published', 'Опубликована'), ('archived', 'Архивная')], default='moderation', max_length=12, verbose_name='статус'),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='title',
            field=models.CharField(max_length=200, verbose_name='название'),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='обновлено'),
        ),
        migrations.AlterField(
            model_name='vacancyskill',
            name='skill',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skill_vacancies', to='taxonomy.skill', verbose_name='навык'),
        ),
        migrations.AlterField(
            model_name='vacancyskill',
            name='vacancy',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vacancy_skills', to='vacancies.vacancy', verbose_name='вакансия'),
        ),
        migrations.AlterField(
            model_name='vacancyskill',
            name='weight',
            field=models.IntegerField(choices=[(1, 'Желательно'), (2, 'Обязательно')], default=2, verbose_name='важность'),
        ),
    ]
